# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: group_40600.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'group_40600.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11group_40600.proto\x12\x08qq_40600\",\n\x04\x42ody\x12$\n\x07\x63ontent\x18\x98\xbd\x02 \x01(\x0b\x32\x11.qq_40600.Content\"7\n\x07\x43ontent\x12\x1a\n\x10status_timestamp\x18\xe3\xc9\x02 \x01(\x03\x12\x10\n\x06marker\x18\x95\xca\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'group_40600_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BODY']._serialized_start=31
  _globals['_BODY']._serialized_end=75
  _globals['_CONTENT']._serialized_start=77
  _globals['_CONTENT']._serialized_end=132
# @@protoc_insertion_point(module_scope)
