// group_msg_table.40801 Protobuf 超集。
// 40801 是重复的摘要/状态快照消息；多态字段保留为 bytes。
syntax = "proto3";
package qq_40801;

message Body {
  repeated Content content = 40801;
}

message Content {
  int64 msg_id = 41501;
  int64 state = 41502;
  int64 f41510 = 41510;
  int64 f41511 = 41511;
  int64 f41512 = 41512;
  int64 f41513 = 41513;
  int64 f41514 = 41514;
  int64 f41516 = 41516;
  int64 f41517 = 41517;
  int64 f41518 = 41518;
  int64 f41519 = 41519;
  int64 f41520 = 41520;
  int64 f41521 = 41521;
  int64 f41522 = 41522;
  int64 f41523 = 41523;
  int64 f41524 = 41524;
  int64 f41525 = 41525;
  int64 f41528 = 41528;
  int64 f41529 = 41529;
  int64 f41530 = 41530;
  int64 f41531 = 41531;
  int64 f41532 = 41532;
  int64 f41533 = 41533;
  int64 f41534 = 41534;
  int64 f41535 = 41535;
  int64 f41536 = 41536;
  int64 f41537 = 41537;
  bytes f41693 = 41693;
  int64 f41694 = 41694;
  int64 f41695 = 41695;
  int64 f41696 = 41696;
  int64 f41697 = 41697;
  int64 f41698 = 41698;
  int64 f43301 = 43301;
  int64 f43302 = 43302;
  bytes f52346 = 52346;
}
